<a href="https://colab.research.google.com/github/saiarun7/Ineuron/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
import array

In [ ]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [ ]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
np.array([1,2,3,4,5,"sudh" , 4+8j,])

array(['1', '2', '3', '4', '5', 'sudh', '(4+8j)'], dtype='<U11')

In [ ]:
np.array([1,2,3,4.5,6.0])

array([1. , 2. , 3. , 4.5, 6. ])

In [ ]:
np.array([[1,3],[3,4]])

array([[1, 3],
       [3, 4]])

In [ ]:
np.array([[1,3],[3,4],[6,7]])

array([[1, 3],
       [3, 4],
       [6, 7]])

In [ ]:
np.array([[1,3],[3,4],[6,7,8]])

<ipython-input-10-2fc331c0f648>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  np.array([[1,3],[3,4],[6,7,8]])


array([list([1, 3]), list([3, 4]), list([6, 7, 8])], dtype=object)

In [ ]:
np.array([[[1,3],[3,4]],[[1,3],[3,4]]])

array([[[1, 3],
        [3, 4]],

       [[1, 3],
        [3, 4]]])

In [ ]:
np.array([1,2,3] , ndmin = 3)

array([[[1, 2, 3]]])

In [ ]:
np.array([1,2,3] , dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
arr = np.array([(1,2) , (4,5)],dtype = [("a",'<i4'), ("b",'<i8')])

In [ ]:
arr

array([(1, 2), (4, 5)], dtype=[('a', '<i4'), ('b', '<i8')])

In [ ]:
type(arr[0][0])

numpy.int32

In [ ]:
type(arr[0][1])

numpy.int64

In [ ]:
arr  = np.array([[1,3],[3,4]])

In [ ]:
arr

array([[1, 3],
       [3, 4]])

In [ ]:
type(arr[0][1])

numpy.int32

In [ ]:
mat = np.matrix(arr)

In [ ]:
l = [3,4,5,76,7]

In [ ]:
np.array(l)

array([ 3,  4,  5, 76,  7])

In [ ]:
np.asarray(l)

array([ 3,  4,  5, 76,  7])

In [ ]:
np.asanyarray(l)

array([ 3,  4,  5, 76,  7])

In [ ]:
np.asanyarray(mat)

matrix([[1, 3],
        [3, 4]])

In [ ]:
np.asarray(mat)

array([[1, 3],
       [3, 4]])

In [ ]:
issubclass(np.ndarray,np.matrix )

False

In [ ]:
arr

array([[1, 3],
       [3, 4]])

In [ ]:
a= arr

In [ ]:
b = np.copy(arr)

In [ ]:
arr[0][0] = 67

In [ ]:
arr

array([[67,  3],
       [ 3,  4]])

In [ ]:
a

array([[67,  3],
       [ 3,  4]])

In [ ]:
b

array([[1, 3],
       [3, 4]])

In [ ]:
arr[-1]

array([3, 4])

In [ ]:
for i in arr:
    print(i)

[67  3]
[3 4]


In [ ]:
type(np.fromfunction(lambda i , j :i==j,(4,4)))

numpy.ndarray

In [ ]:
np.fromfunction(lambda i , j :i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [ ]:
np.fromfunction(lambda i , j :i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [ ]:
np.fromfunction(lambda i , j :i**j,(3,3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

In [ ]:
np.fromfunction(lambda i , j :i/j,(3,3))

<ipython-input-66-a854da4aa4ba>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i , j :i/j,(3,3))
<ipython-input-66-a854da4aa4ba>:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i , j :i/j,(3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [ ]:
0/0

ZeroDivisionError: division by zero

In [ ]:
1/0

ZeroDivisionError: division by zero

In [ ]:
gen = (i*i for i in range(5))

In [ ]:
def test(x):
    yield x 

In [ ]:
test(5)

<generator object test at 0x000002858582D4A0>

In [ ]:
gen
for i in gen :
    print(i)

In [ ]:
np.fromiter(range(5),dtype= int)

array([0, 1, 2, 3, 4])

In [ ]:
np.fromstring('1,3,4,5,5' , sep = ',', dtype= int)

array([1, 3, 4, 5, 5])

In [ ]:
np.fromstring("456 456 3454 34543" ,sep = ' ', dtype= complex)

array([  456.+0.j,   456.+0.j,  3454.+0.j, 34543.+0.j])

In [ ]:
l = [3,4,5,6,7,8]

In [ ]:
arr = np.array(l)

In [ ]:
arr1 = np.array([[1,2,3,4] , [2,3,4,5] , [4,5,6,7]])

In [ ]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr1.ndim

2

In [ ]:
arr1.size

12

In [ ]:
arr1.shape


(3, 4)

In [ ]:
arr1.dtype

dtype('int32')

In [ ]:
arr

array([3, 4, 5, 6, 7, 8])

In [ ]:
arr.size

6

In [ ]:
arr.ndim

1

In [ ]:
arr.shape

(6,)

In [ ]:
arr2 = np.array([[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]])

In [ ]:
arr2


array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [ ]:
arr2.size

16

In [ ]:
arr2.ndim

3

In [ ]:
arr2.shape

(2, 2, 4)

In [ ]:
arr4 = np.array([[[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]]])

In [ ]:
arr4

array([[[[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]]]])

In [ ]:
arr4.ndim

4

In [ ]:
arr4.shape

(1, 4, 2, 4)

In [ ]:
list(range(6.6,9,.3))

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
np.arange(9,6.6,-.3)

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6])

In [ ]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.ones((2,3,1))+5

array([[[6.],
        [6.],
        [6.]],

       [[6.],
        [6.],
        [6.]]])

In [ ]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.empty((3,4))

array([[1.36976717e-311, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 8.60952352e-072, 4.22470126e-090,
        1.80194451e+185],
       [8.31857002e-072, 1.79218578e+160, 3.99910963e+252,
        1.29200800e+161]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.linspace([1,6],4,endpoint=False,axis=1)

array([[1.  , 1.06, 1.12, 1.18, 1.24, 1.3 , 1.36, 1.42, 1.48, 1.54, 1.6 ,
        1.66, 1.72, 1.78, 1.84, 1.9 , 1.96, 2.02, 2.08, 2.14, 2.2 , 2.26,
        2.32, 2.38, 2.44, 2.5 , 2.56, 2.62, 2.68, 2.74, 2.8 , 2.86, 2.92,
        2.98, 3.04, 3.1 , 3.16, 3.22, 3.28, 3.34, 3.4 , 3.46, 3.52, 3.58,
        3.64, 3.7 , 3.76, 3.82, 3.88, 3.94],
       [6.  , 5.96, 5.92, 5.88, 5.84, 5.8 , 5.76, 5.72, 5.68, 5.64, 5.6 ,
        5.56, 5.52, 5.48, 5.44, 5.4 , 5.36, 5.32, 5.28, 5.24, 5.2 , 5.16,
        5.12, 5.08, 5.04, 5.  , 4.96, 4.92, 4.88, 4.84, 4.8 , 4.76, 4.72,
        4.68, 4.64, 4.6 , 4.56, 4.52, 4.48, 4.44, 4.4 , 4.36, 4.32, 4.28,
        4.24, 4.2 , 4.16, 4.12, 4.08, 4.04]])

In [ ]:
np.logspace([2],[3] , axis = 0)

array([[ 100.        ],
       [ 104.81131342],
       [ 109.8541142 ],
       [ 115.13953993],
       [ 120.67926406],
       [ 126.48552169],
       [ 132.57113656],
       [ 138.94954944],
       [ 145.63484775],
       [ 152.64179672],
       [ 159.98587196],
       [ 167.68329368],
       [ 175.75106249],
       [ 184.20699693],
       [ 193.06977289],
       [ 202.35896477],
       [ 212.09508879],
       [ 222.29964825],
       [ 232.99518105],
       [ 244.20530945],
       [ 255.95479227],
       [ 268.26957953],
       [ 281.1768698 ],
       [ 294.70517026],
       [ 308.88435965],
       [ 323.74575428],
       [ 339.32217719],
       [ 355.64803062],
       [ 372.75937203],
       [ 390.69399371],
       [ 409.49150624],
       [ 429.19342601],
       [ 449.8432669 ],
       [ 471.48663635],
       [ 494.17133613],
       [ 517.94746792],
       [ 542.86754393],
       [ 568.9866029 ],
       [ 596.36233166],
       [ 625.05519253],
       [ 655.12855686],
       [ 686.648

In [ ]:
d = np.linspace(4,7,40)

In [ ]:
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [ ]:
d.ndim

1

In [ ]:
d.shape

(40,)

In [ ]:
d.reshape(40,1)

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [ ]:
d.reshape(1,4,10)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769],
        [4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923],
        [6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [ ]:
np.logspace(2,5,10)


array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [ ]:
np.random.rand(3)

array([0.55386094, 0.36578256, 0.18724663])

In [ ]:
np.random.randn(5)

array([-0.99738232, -0.29937244, -1.6336683 , -0.37804326, -0.73977523])

In [ ]:
np.random.randn(2,2,3)

array([[[ 1.47338029,  0.61271404, -1.4075616 ],
        [ 0.76839332, -0.12216353, -0.09569462]],

       [[ 0.84685866,  0.53664687,  0.38711111],
        [-0.32053034,  0.53523058, -0.76029515]]])

In [ ]:
np.random.randint(5,60, (4,4))

array([[30, 50, 58, 40],
       [10, 51, 38, 26],
       [19, 10, 14, 55],
       [ 8, 32, 59, 39]])

In [ ]:
np.random.randn(2,2,3)

array([[[-0.18658137, -2.62084719,  0.05678706],
        [ 0.80066306,  0.32081787,  0.04011781]],

       [[-0.67044971, -0.26951513,  1.56406203],
        [ 1.70218004, -1.43323041, -1.91830673]]])

In [ ]:
arr = np.random.randint(3,9, ( 3,3))

In [ ]:
arr

array([[5, 3, 5],
       [7, 6, 4],
       [7, 6, 7]])

In [ ]:
arr.reshape(1,9)

array([[5, 3, 5, 7, 6, 4, 7, 6, 7]])

In [ ]:
arr.reshape(9,1)

array([[5],
       [3],
       [5],
       [7],
       [6],
       [4],
       [7],
       [6],
       [7]])

In [ ]:
arr.reshape(1,1,9)

array([[[5, 3, 5, 7, 6, 4, 7, 6, 7]]])

In [ ]:
arr.reshape(3,3,1)

array([[[5],
        [3],
        [5]],

       [[7],
        [6],
        [4]],

       [[7],
        [6],
        [7]]])

In [ ]:
arr.reshape(3,-198979)

array([[5, 3, 5],
       [7, 6, 4],
       [7, 6, 7]])

In [ ]:
arr.reshape(1,-145654656)

array([[5, 3, 5, 7, 6, 4, 7, 6, 7]])

In [ ]:
arr

array([[5, 3, 5],
       [7, 6, 4],
       [7, 6, 7]])

In [ ]:
arr.max()

7

In [ ]:
arr.min()

3

In [ ]:
arr = np.random.randint(4,100, (5,5))

In [ ]:
arr

array([[33, 90, 97, 11,  4],
       [49, 40, 83, 38, 64],
       [ 6, 49, 99, 86, 96],
       [48, 58, 91, 66,  8],
       [31, 24, 34, 64, 62]])

In [ ]:
arr[3: , 3:]

array([[66,  8],
       [64, 62]])

In [ ]:
arr[:,[1,3]]

array([[90, 11],
       [40, 38],
       [49, 86],
       [58, 66],
       [24, 64]])

In [ ]:
arr

array([[33, 90, 97, 11,  4],
       [49, 40, 83, 38, 64],
       [ 6, 49, 99, 86, 96],
       [48, 58, 91, 66,  8],
       [31, 24, 34, 64, 62]])

In [ ]:
arr[arr>10]

array([33, 90, 97, 11, 49, 40, 83, 38, 64, 49, 99, 86, 96, 48, 58, 91, 66,
       31, 24, 34, 64, 62])

In [ ]:
arr>10

array([[ True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True]])

In [ ]:
arr

array([[33, 90, 97, 11,  4],
       [49, 40, 83, 38, 64],
       [ 6, 49, 99, 86, 96],
       [48, 58, 91, 66,  8],
       [31, 24, 34, 64, 62]])

In [ ]:
arr * arr

array([[1089, 8100, 9409,  121,   16],
       [2401, 1600, 6889, 1444, 4096],
       [  36, 2401, 9801, 7396, 9216],
       [2304, 3364, 8281, 4356,   64],
       [ 961,  576, 1156, 4096, 3844]])

In [ ]:
arr1 = np.random.randint(2,4,(3,3))

In [ ]:
arr2 = np.random.randint(2,4,(3,3))

In [ ]:
arr1

array([[2, 3, 3],
       [3, 2, 3],
       [3, 3, 2]])

In [ ]:
arr2

array([[2, 2, 3],
       [3, 3, 3],
       [3, 2, 3]])

In [ ]:
arr1*arr2

array([[4, 6, 9],
       [9, 6, 9],
       [9, 6, 6]])

In [ ]:
arr1@arr2

array([[22, 19, 24],
       [21, 18, 24],
       [21, 19, 24]])

In [ ]:
arr/0

<ipython-input-249-39e2cbdaf753>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [ ]:
arr**2

array([[1089, 8100, 9409,  121,   16],
       [2401, 1600, 6889, 1444, 4096],
       [  36, 2401, 9801, 7396, 9216],
       [2304, 3364, 8281, 4356,   64],
       [ 961,  576, 1156, 4096, 3844]], dtype=int32)

In [ ]:
arr = np.zeros((3,4))

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
a = np.array([1,2,3,5])

In [ ]:
a


array([1, 2, 3, 5])

In [ ]:
arr + a 

array([[1., 2., 3., 5.],
       [1., 2., 3., 5.],
       [1., 2., 3., 5.]])

In [ ]:
arr+ 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
b = np.array([5,6,7])

In [ ]:
b

array([5, 6, 7])

In [ ]:
b.reshape(3,1) + arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [ ]:
b

array([5, 6, 7])

array([5, 6, 7])

In [ ]:
b = np.array([[5,6,7]])

In [ ]:
b.T + arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr = np.random.rand(5,4)

In [ ]:
arr

array([[0.67941063, 0.39266408, 0.3690279 , 0.24322169],
       [0.73639163, 0.0401203 , 0.93684485, 0.61136987],
       [0.91075051, 0.90249311, 0.48110496, 0.24793594],
       [0.95043203, 0.31504451, 0.25094332, 0.6629506 ],
       [0.12575233, 0.45982773, 0.34866419, 0.31466519]])

In [ ]:
np.sqrt(arr)

array([[0.82426369, 0.62662914, 0.60747666, 0.49317511],
       [0.85813264, 0.20030052, 0.96790746, 0.78190144],
       [0.9543325 , 0.94999637, 0.6936173 , 0.49793166],
       [0.97490104, 0.56128826, 0.50094243, 0.81421778],
       [0.35461575, 0.67810599, 0.59047794, 0.56095025]])

In [ ]:
np.exp(arr)

array([[1.97271474, 1.48092083, 1.44632795, 1.27535132],
       [2.08838623, 1.04093599, 2.55191703, 1.84295428],
       [2.48618775, 2.46574282, 1.61786108, 1.28137784],
       [2.58682701, 1.3703203 , 1.28523724, 1.94050956],
       [1.13400128, 1.58380112, 1.41717322, 1.3698006 ]])

In [ ]:
np.log10(arr)

array([[-0.16786766, -0.40597883, -0.4329408 , -0.6139977 ],
       [-0.13289116, -1.39663583, -0.02833232, -0.21369597],
       [-0.04060057, -0.04455611, -0.31776017, -0.60566052],
       [-0.02207894, -0.50162808, -0.60042436, -0.17851883],
       [-0.90048395, -0.33740484, -0.45759265, -0.5021513 ]])

In [ ]:
arr1 = np.random.randint(2,5, (5,5))

In [ ]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.60205999, 0.60205999, 0.47712125],
       [0.47712125, 0.60205999, 0.60205999, 0.60205999, 0.47712125],
       [0.47712125, 0.60205999, 0.30103   , 0.60205999, 0.30103   ],
       [0.47712125, 0.30103   , 0.30103   , 0.47712125, 0.47712125],
       [0.60205999, 0.47712125, 0.60205999, 0.60205999, 0.47712125]])

In [ ]:
arr1

array([[3, 3, 4, 4, 3],
       [3, 4, 4, 4, 3],
       [3, 4, 2, 4, 2],
       [3, 2, 2, 3, 3],
       [4, 3, 4, 4, 3]])

In [ ]:
np.random.seed(13)

In [ ]:
np.random.seed(30)
np.random.rand(2,4)

array([[0.64414354, 0.38074849, 0.66304791, 0.16365073],
       [0.96260781, 0.34666184, 0.99175099, 0.2350579 ]])